---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-11-21T11:47:15Z"
  name: carts-canary
  resourceVersion: "934303"
  selfLink: /api/v1/namespaces/sockshop-production/services/carts
  uid: a9f1d36c-0c54-11ea-86c5-42010a84003b
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
