apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-11-21T11:39:41Z"
  name: carts-canary
  resourceVersion: "932454"
  selfLink: /api/v1/namespaces/sockshop-staging/services/carts
  uid: 9b14e76a-0c53-11ea-86c5-42010a84003b
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
